version: '3.1'

services:
  broker:
    container_name: celery-broker
    image: redis

  worker:
    container_name: celery-worker
    build:
      context: ./worker
      dockerfile: Dockerfile-worker
    depends_on:
      - broker
    links:
      - broker:${REDIS_HOST_NAME}
    restart: on-failure
    command:
      - bash
      - -c
      - |
        ./wait-for-it.sh ${REDIS_HOST_NAME}:${REDIS_PORT} -t 10 \
        -- celery -A tasks worker -Q sqrt_queue,fibo_queue,webcrawler_queue -l INFO

  client:
    container_name: celery-client
    build:
      context: ./client
      dockerfile: Dockerfile-client
    depends_on:
      - worker
      - broker
    links:
      - broker:${REDIS_HOST_NAME}